### ISSUE TITLE
Mettre le bouton supprimer pour le dernier lieu météo favori

### ISSUE THREAD

**Issue by SybilleCaffiau** [appsgate2015/appsgate#390]
Lorsqu'il n'y a qu'un lieu météo favori, le bouton "Supprimer" n'est pas présent. Il disparait dès qu'on a supprimer tous les autres lieux favoris

**Comment by BidoisMorgan** [comment]
Pas pour maintenant. Eventuellement Service Technology Adapter plus tard.
