### ISSUE TITLE
Correction de l'IHM du lecteur multimédia (niveau 2)

### ISSUE THREAD

**Issue by CamilleLenoir** [appsgate2015/appsgate#391]
![image](https://cloud.githubusercontent.com/assets/7642063/5229225/ec014470-7714-11e4-9438-9785e5568932.png)

![capture d ecran 2014-11-28 a 15 34 16](https://cloud.githubusercontent.com/assets/7642063/5229202/8bee3f70-7714-11e4-99bb-43b89e2fa04c.png)

![capture d ecran 2014-11-28 a 15 41 27](https://cloud.githubusercontent.com/assets/7642063/5229237/1481dab8-7715-11e4-81e1-32bd79c43dec.png)

On choisit un média:
![capture d ecran 2014-11-28 a 15 42 33](https://cloud.githubusercontent.com/assets/7642063/5229246/32427d6e-7715-11e4-9d90-90a08c603c55.png)
![capture d ecran 2014-11-28 a 15 43 05](https://cloud.githubusercontent.com/assets/7642063/5229266/66e2edc4-7715-11e4-8a1d-83c71128be5c.png)
![capture d ecran 2014-11-28 a 15 43 12](https://cloud.githubusercontent.com/assets/7642063/5229267/696f31ec-7715-11e4-95e1-4ef4bcd3c878.png)
![capture d ecran 2014-11-28 a 15 43 19](https://cloud.githubusercontent.com/assets/7642063/5229268/6c8f846c-7715-11e4-8abc-ed57fca08c1f.png)
![capture d ecran 2014-11-28 a 15 43 24](https://cloud.githubusercontent.com/assets/7642063/5229270/6f7bbde4-7715-11e4-8296-df1bb1760a46.png)
![capture d ecran 2014-11-28 a 15 43 30](https://cloud.githubusercontent.com/assets/7642063/5229271/72182920-7715-11e4-8ebe-a44c01efe26d.png)
![capture d ecran 2014-11-28 a 15 43 36](https://cloud.githubusercontent.com/assets/7642063/5229273/77db0526-7715-11e4-995f-16ee5c9023d9.png)
![capture d ecran 2014-11-28 a 15 43 41](https://cloud.githubusercontent.com/assets/7642063/5229275/7ad7d830-7715-11e4-8b76-982e2434745d.png)
![capture d ecran 2014-11-28 a 15 43 46](https://cloud.githubusercontent.com/assets/7642063/5229277/7ddf4ec8-7715-11e4-9926-5e536417cc35.png)
![capture d ecran 2014-11-28 a 15 43 54](https://cloud.githubusercontent.com/assets/7642063/5229279/8059cb60-7715-11e4-819d-cc7fce89b00a.png)
![capture d ecran 2014-11-28 a 15 44 00](https://cloud.githubusercontent.com/assets/7642063/5229281/82783436-7715-11e4-90bb-58ba8063804a.png)

**Comment by BidoisMorgan** [comment]
Ne pas faire.
