### ISSUE TITLE
TraceMan fait planter l'historique lorsque "id" undefined sur la bdd

### ISSUE THREAD

**Issue by snybril** [appsgate2015/appsgate#399]
Check à l'arrache pour éviter l'exception, à vérifier sur le commit f8a0b284d474fe541bbe6de79eb7a3a78a64ed49

(à noter, en dehors de la découverte de la CoreTV, ce bug ne se produit pas)

**Comment by jrcourtois** [comment]
Rien à rajouter, il est toujours mieux d'éviter les NPE ou les get sur un élément JSON qui n'existe pas
