### ISSUE TITLE
clignoter N seconde dure 0 secondes

### ISSUE THREAD

**Issue by AlexDmr** [appsgate2015/appsgate#425]
Problème lorsqu'on a un programme du type :  
 A chaque fois que on appuie sur bouton alors
       Allumer lampe en bleu
       Faire clignoter pendant 5 secondes rapidement
       Allumer lampe en blanc
       Eteindre lampe

**Comment by jandernascimento** [comment]
En effet, on considère le clignotement comme un état, donc la lampe est ou allumé, ou éteint ou en clignotement.  Donc si on demande le changement d’état on exécute le changement sans contraints.
J'ai maintenu le même comportement d'avant. Auparavant on exprimé **faire clignoter** (qui implicitement devrait clignoter pendant 30" ) mais si à la suite on demande la lampe de se éteint on attendait pas les 30 seconds de clignotement. On été obligé de rajouter un **attendre** pour voir le clignotement.
Si on change ça, faut être conscient que la lampe sera complètement bloqué pendant ce temps, c'est à dire que personne pourrais changer son état tant quelle n'a pas fini de clignoter.
Je rajoute le label "A discuter"

**Comment by AlexDmr** [comment]
J'aurais dit que seule l'instruction "faire clignoter" a une durée, ça ne devrait pas empêcher ailleurs (via les commandes directes) d'éteindre la lampe, dans ce cas l'instruction "faire clignoter" devrait se terminer suite à l'action sur la lampe. Qu'en pensez vous?

**Comment by jrcourtois** [comment]
On peut imaginer rajouter dans le clavier de mot l'instruction attendre, ou plein de solutions... Je pense qu'il faut en discuter avant de rentrer dans des essais plus pointus... A la base, j'avais demandé à Jander d'avoir le même comportement que l'ancien + le fait de pouvoir s'abonner à l'état de la lampe. Le problème, c'est qu'avec tous ces paramètres, on a d'autres problèmes sans avoir résolus les anciens.

**Comment by jandernascimento** [comment]
Le comportement reste le comportement actuelle. Les expe utilisateur nous diront si il faudrait on le change ou pas.
