### ISSUE TITLE
CHMI script fails

### ISSUE THREAD

**Issue by jandernascimento** [appsgate2015/appsgate#430]
> Description
 
Dans certain cas, le IHM génére une exception qui empêche là mis à jour le l'interface (quand un nouvelle dispositif aparait par example;

> JS Exception

received MessageEvent {ports: Array[0], data: "{"varName":"activeFace","objectId":"domicube","value":"5","oldValue":""}", source: null, lastEventId: "", origin: "ws://localhost:8087"…} communicator.js:121
received MessageEvent {ports: Array[0], data: "{"removeDevice":{"objectId":"domicube"}}", source: null, lastEventId: "", origin: "ws://localhost:8087"…} communicator.js:121
Uncaught TypeError: Cannot read property 'forEach' of undefined devicebytype.js:293Backbone.View.extend.render devicebytype.js:293triggerEvents backbone.js:207Backbone.Events.trigger backbone.js:146_.extend.remove backbone.js:651Backbone.Collection.extend.removeDevice devices.js:156(anonymous function) devices.js:59triggerEvents backbone.js:205Backbone.Events.trigger backbone.js:146Communicator.handleMessage communicator.js:136

**Comment by jrcourtois** [comment]
Pourrais tu préciser les conditions dans lesquels ce problème apparait, et s'il apparaît toujours ?

**Comment by jrcourtois** [comment]
Unable to reproduce
