### ISSUE TITLE
Remonté l'info de la charge de la batterie au IHM

### ISSUE THREAD

**Issue by jandernascimento** [appsgate2015/appsgate#448]
> Description

Remonté l'info de la charge de la batterie au IHM

> Remarque 

Partiellement fait sur la branch domicubebatterystatus (regarder le commentaire du commit pour en savoir plus les détailles)

**Comment by joellecoutaz** [comment]
Hé, good!
On 15 Jan 2015, at 15:25, jandernascimento wrote:

> Description
> 
> Remonté l'info de la charge de la batterie au IHM
> 
> Remarque
> 
> Partiellement fait sur la branch domicubebatterystatus (regarder le commentaire du commit pour en savoir plus les détailles)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

*************************************************************************
Joelle COUTAZ, Professeur émérite
Lab. LIG (laboratoire d'Informatique de Grenoble)
41 rue des Mathématiques, 38400 St-Martin d'Hères, France, http://iihm.imag.fr/coutaz, tel. 33 4 76 51 48 54
*************************************************************************
