### ISSUE TITLE
Historique_Domicube: disparition et mauvais nom de type

### ISSUE THREAD

**Issue by CamilleLenoir** [appsgate2015/appsgate#454]
on a "Groups.domicube" comme type

et alors  que le Domicube fonctionne bien, il n'apparait plus dans Historique et Direct

**Comment by joellecoutaz** [comment]
Le domicube doit ds la ligne de temps indiquer sa nouvelle face. Actuellemnt, il n'ya que le msg connecté/reconnecté/déconnecté ds la bulle.
