### ISSUE TITLE
La couleur des ampoules dans la TL et dans l'IHM n'est pas cohérente

### ISSUE THREAD

**Issue by jrcourtois** [appsgate2015/appsgate#459]
Plusieurs soucis : il faut vérifier que les états sont tous retranscrits dans la time line

L'algorithme de calcul de la couleur n'est peut-être pas le même dans les 2 cas.

L'IHM de choix de couleur n'est pas forcément la plus utilisable...

**Comment by jandernascimento** [comment]
C'est rien avoir avec l'implem da la lamp JR. ça c'est IHM. Je suis en train de verifier si c'est un probleme avec le widget ou pas. Mais je suis sur qui non, je viens de trouve mon commit ou je corrigé cette issue, et la il marche. Quelque changement ailleurs qui a généré cette issue la.

**Comment by snybril** [comment]
Changer de couleur -> aller sur un autre device -> revenir sur la lampe : la couleur est restée à celle d'avant

**Comment by jandernascimento** [comment]
Fixed on the commit https://github.com/appsgate2015/appsgate/commit/ea9512ad57e1bb314b60b0614402fdb89155a7cf
