### ISSUE TITLE
Media Server tourne en boucle sur la commande "browse"

### ISSUE THREAD

**Issue by joellecoutaz** [appsgate2015/appsgate#462]
A la suite d'un clic sur choose un media, la fenetre pop up apparait et le msg browse. Alors le curseur tourne en rond.
Ce test a été fait sur le Yellow.

**Comment by jrcourtois** [comment]
Je pense qu'il s'agit d'un problème de temps de connexion au réseau. Si UPNP fonctionne correctement, on n'a pas ce problème. J'aurais tendance à dire qu'il s'agit d'un problème connu. Camille peux tu le référencer ?

**Comment by snybril** [comment]
Pas réussi à reproduire, résolu par "hasard" ?

A réouvrir si besoin

**Comment by snybril** [comment]
Le bug se reproduit systématiquement quand aucun media browser n'est présent

**Comment by snybril** [comment]
Corrigé côté télécommande, pas dans les programmes
