### ISSUE TITLE
Incoherence état pg ds IHM de pilotage

### ISSUE THREAD

**Issue by joellecoutaz** [appsgate2015/appsgate#463]
Ds la liste des pgs, on trouve un pg a l'arrêt avec une pastille rouge alors qu'elle aurait du être en vert. On l'édite et la pastille passe en vert.

**Comment by CamilleLenoir** [comment]
Quelque que chose de proche:
j'ai écrit un programme pour envoyer un mail.
On perd internet et donc le service mail -> le programme passe logiquement en orange, pourtant, en édition, il est systématiquement en vert

**Comment by jrcourtois** [comment]
Voir #452
