### ISSUE TITLE
Historique_Mauvais icônes à la place de la loupe pour les contacts et la luminosité

### ISSUE THREAD

**Issue by CamilleLenoir** [appsgate2015/appsgate#470]

**Comment by CamilleLenoir** [comment]
![capture d ecran 2015-02-02 a 12 42 49](https://cloud.githubusercontent.com/assets/7642063/6000742/e01faae2-aae1-11e4-9e1d-e6ead0596e5a.png)

**Comment by CamilleLenoir** [comment]
aussi pour l'interrupteur à carte et les interrupteurs

**Comment by jrcourtois** [comment]
C'est pas un bug, c'est une fonctionnalité... S'il n'y a qu'un seul événement, on lui met le picto qui correspond à son état.
