### ISSUE TITLE
Error GrammarDescrption

### ISSUE THREAD

**Issue by BidoisMorgan** [appsgate2015/appsgate#473]
Lorsque j'arrive sur appsgate, j'ai deux lignes d'erreurs qui sont tracées sur le serveur : 

ERROR a.lig.ehmi.spec.GrammarDescription -- Command not found (getCurrentTimeInMillis) for type Clock
ERROR a.lig.ehmi.spec.GrammarDescription -- Command not found (getTimeFlowRate) for type Clock

J'ai certains de mes programmes qui font références à l'horloge d'appsgate.

**Comment by snybril** [comment]
J’ai vu ça aussi,
ça le fait sur plusieurs Devices (pas seulement la clock), apparement une description des commandes ont été ajoutées dans les grammaires json (pour TraceMan ?)
De ce que j’ai vu, ça n’empêche pas les commandes de s’executer…
(après je sais pas trop à quoi ça sert, p’tet que JR sait)
  Thibaud

**Comment by snybril** [comment]
renommé l'issue.  Car ça concerne potentiellement tous les services.

plutôt que d'ajouter à la main les lignes dans le grammar.json, peut être faire une introspection automatique ? (lors du découverte par CHMI).

**Comment by jrcourtois** [comment]
J'avoue que le fichier grammar.json n'est sans doute pas la meilleure solution, mais je ne pense pas que l'introspection soit une bonne solution. On veut pouvoir faire un peu de tri sur les méthodes qui sont rencontrées.

**Comment by snybril** [comment]
encore des manques, par exemple fonction play des lecteurs multimédia avec 2 arguments
(URL + name)
A discuter:
Pourquoi l'introspection n'est pas une bonne idée ?

**Comment by jrcourtois** [comment]
Disons que l'introspection est une bonne idée, mais, je ne sais pas comment faire, et ça me semble plus couteux que de rajouter dans le ficher grammar.json
