### ISSUE TITLE
Impossible d'allumer une HUE avec une couleur

### ISSUE THREAD

**Issue by BidoisMorgan** [appsgate2015/appsgate#487]
Dans un programme, impossible d'allumer une lampe avec une couleur autre que 'blanc'

**Comment by jandernascimento** [comment]
Solved before, but forgot to push the code.

**Comment by jrcourtois** [comment]
Jander si tu lis encore tes mails, j'ai pas l'impression que ce soit corrigé...

**Comment by snybril** [comment]
Heu, chez moi ça fonctionne, ou alors j'ai pas compris le pb
