### ISSUE TITLE
Dépendances_ Incohérences entre les deux services

### ISSUE THREAD

**Issue by CamilleLenoir** [appsgate2015/appsgate#497]
![capture d ecran 2015-02-25 a 09 27 13](https://cloud.githubusercontent.com/assets/7642063/6367417/391d234c-bcd3-11e4-89e7-68a2a35c45be.png)
![capture d ecran 2015-02-25 a 09 27 19](https://cloud.githubusercontent.com/assets/7642063/6367419/3c57ae88-bcd3-11e4-9f7a-e07a7e64bf99.png)

- Pour le service Météo: une bulle par Lieux + le nom du Lieu
- Pour le service Mail: une seule bulle (peu importe le nombre de destinataires) + "Destinataire mail favori"
-> avoir autant de bulle que de destinataire et avoir le début de l'adresse mail + "..." pour chaque bulle

**Comment by BidoisMorgan** [comment]
Pas possible à faire. 
Pour les lieux de météo, un service météo est fait pour chaque lieu, alors que pour le service mail, on a qu'un service mail qui peut pointer vers différentes adresses. De la même manière, le service synthèse vocale sera tout seul peu importe le nombre de message qu'il créera.
