### ISSUE TITLE
Changement nom équipement non répercuté

### ISSUE THREAD

**Issue by snybril** [appsgate2015/appsgate#504]
(testé avec renommage interupteur)

dans dépendances -> OK
 dans historique, onglet direct -> OK
 dans historique, onglet historique -> NOK
 dans programmes qui référencent l'équipement -> NOK

**Comment by jrcourtois** [comment]
Dans l'onglet historique, c'est le comportement attendu + ou -

Je regarde pour les programmes (je pense qu'il s'agit d'une régression)...
