### ISSUE TITLE
Impossible d'arrêter appsgate

### ISSUE THREAD

**Issue by jrcourtois** [appsgate2015/appsgate#510]
Est-ce du au passage à Apam 0.8, toujours est il que pour arrêter appsgate, je suis systématiquement obligé de faire un kill -9

**Comment by snybril** [comment]
On est pas passé à apam 0.0.8 pour l'instant, donc ce n'est pas ça.

Par contre j'ai rencontré ce bug sur les mini pc, pas sur mon mac.
