### ISSUE TITLE
Pendant que sur état de programme : Une fois sur deux

### ISSUE THREAD

**Issue by BidoisMorgan** [appsgate2015/appsgate#520]
Quand on fait un pendant que sur l'état d'un programme, cela ne marche qu'une fois sur deux. 
C'est à dire que la première fois que le programme (qu'on écoute) va s'activer, l'instruction va marcher. Mais une fois qu'on éteint et qu'on rallume le programme (qu'on écoute) l'instruction ne marchera pas.

**Comment by jrcourtois** [comment]
Pas réussi à reproduire....
