### ISSUE TITLE
Problème d'arrêt de la plateforme

### ISSUE THREAD

**Issue by snybril** [appsgate2015/appsgate#534]
Les dépendances croisées lors des opération de remove empêchent la plateforme de s'arrêter.
(notamment les composants qui utilisent la base de données, qui attendent cette base alors quelle est arrêtée)
-> Hypothèse de German: regression introduite par apam 0.0.8 (depuis que les remove d'instances fonctionnent)

Workaround: script kill.sh de JR (pas très adapté au déploiement sur mini-pc)

**Comment by jrcourtois** [comment]
Still the issue
  139|Active     |    1|UPnP Adapter (based on UPnP BaseDriver) (1.0.0)
  140|Active     |    1|Core switch sensor specification (1.0.0)
  141|Stopping   |    1|ConfigurableClockImpl (1.0.0)
  142|Resolved   |    1|Core SmartPlug specification (1.0.0)
  143|Resolved   |    1|Temperature sensor implementation (1.0.0)
  144|Resolved   |    1|Extended Weather Observer specification (1.0.0)
  145|Resolved   |    1|DevicePropertiesTableImpl OSGi Bundle (1.0.0)
  146|Resolved   |    1|Core undefined sensor specification (1.0.0)
  147|Resolved   |    1|Core occuancy specification (1.0.0)
